import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-full" lang="en">
      <body className={`${inter.className} h-full`}>
        <div className="min-h-full mx-auto max-w-3xl bg-gray-100">
          <div
            style={{ backgroundImage: "url(/channel_bg.jpeg)" }}
            className="bg-center pb-64"
          />
          {children}
        </div>
      </body>
    </html>
  );
}
